name: Request Integration Access
description: Use this issue to provide access to selected customers
title: "Request Access: "
assignees:
  - vramana
body:
- id: domains
  type: textarea
  attributes:
    label: Domains
    placeholder: Enter the affected domains
- type: checkboxes
  id: terms
  attributes:
    label: Preview Integrations
    options:
      - label: Eagle Eye Integration
        
