name: Issue Report
description: Report an issue with the app
title: "[Request Preview]: "
assignees:
  - vramana
body:
- id: domains
  type: textarea
  attributes:
    label: Domains
    placeholder: Enter the affected domains
- id: app_name
  type: textarea
  attributes:
    label: App Name
    placeholder: Enter the name of the app
- type: checkboxes
  id: terms
  attributes:
    label: Eagle Eye Integration
    description: Connects Eagle Eye cameras 
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
